import React from 'react';
import ReactPaginate from 'react-paginate';
import Navbar from '../../components/Navbar';
import { BsChevronLeft, BsChevronRight } from 'react-icons/bs';
import { useState } from 'react';
import OneOrder from '../../components/SellerDashboard/OneOrder';

function MyPurchases() {
  // constants
  const [items, setItems] = useState([
    {
      typeOfCustumer: 'غيث عثمان',
      TypeOfProduct:
        'كنزة صوف قطن شتوية صيفية ربيعية خريفية موجودة في شارع الحضارة ',
      TypeBuy: 'WePay',
      Date: '14/1/2001',
      img: '../../defaultProduct.jfif',
      sizes: ['XL', 'L', 'M', 'S', 'XL', 'XXL', '3XL', '4XL', '5XL', '6XL'],
      colors: ['#50d71e', '#000000', '#50d71e', '#000000'],
      fullName: 'غيث فيصل عثمان',
      email: 'ghaethoo2001.go@gmail.com',
      number: '+963937082264',
      city: 'حمص',
      Address: ' شارع الحضارة',
    },
    {
      typeOfCustumer: 'غيث عثمان',
      TypeOfProduct: 'كنزة',
      TypeBuy: 'WePay',
      Date: '14/1/2001',
      img: '../../defaultProduct.jfif',
      sizes: ['XL', 'L', 'M', 'S'],
      colors: ['#50d71e', '#000000', '#50d71e', '#000000'],
      fullName: 'غيث فيصل عثمان',
      email: 'ghaethoo2001.go@gmail.com',
      number: '+963937082264',
      city: 'حمص',
      Address: ' شارع الحضارة',
    },
    {
      typeOfCustumer: 'غيث عثمان',
      TypeOfProduct: 'كنزة',
      TypeBuy: 'WePay',
      Date: '14/1/2001',
      img: '../../defaultProduct.jfif',
      sizes: ['XL', 'L', 'M', 'S'],
      colors: ['#50d71e', '#000000', '#50d71e', '#000000'],
      fullName: 'غيث فيصل عثمان',
      email: 'ghaethoo2001.go@gmail.com',
      number: '+963937082264',
      city: 'حمص',
      Address: ' شارع الحضارة',
    },
    {
      typeOfCustumer: 'غيث عثمان',
      TypeOfProduct: 'كنزة',
      TypeBuy: 'WePay',
      Date: '14/1/2001',
      img: '../../defaultProduct.jfif',
      sizes: ['XL', 'L', 'M', 'S'],
      colors: ['#50d71e', '#000000', '#50d71e', '#000000'],
      fullName: 'غيث فيصل عثمان',
      email: 'ghaethoo2001.go@gmail.com',
      number: '+963937082264',
      city: 'حمص',
      Address: ' شارع الحضارة',
    },
    {
      typeOfCustumer: 'غيث عثمان',
      TypeOfProduct: 'كنزة',
      TypeBuy: 'WePay',
      Date: '14/1/2001',
      img: '../../defaultProduct.jfif',
      sizes: ['XL', 'L', 'M', 'S'],
      colors: ['#50d71e', '#000000', '#50d71e', '#000000'],
      fullName: 'غيث فيصل عثمان',
      email: 'ghaethoo2001.go@gmail.com',
      number: '+963937082264',
      city: 'حمص',
      Address: ' شارع الحضارة',
    },
    {
      typeOfCustumer: 'غيث عثمان',
      TypeOfProduct: 'كنزة',
      TypeBuy: 'WePay',
      Date: '14/1/2001',
      img: '../../defaultProduct.jfif',
      sizes: ['XL', 'L', 'M', 'S'],
      colors: ['#50d71e', '#000000', '#50d71e', '#000000'],
      fullName: 'غيث فيصل عثمان',
      email: 'ghaethoo2001.go@gmail.com',
      number: '+963937082264',
      city: 'حمص',
      Address: ' شارع الحضارة',
    },
    {
      typeOfCustumer: 'غيث عثمان',
      TypeOfProduct: 'كنزة',
      TypeBuy: 'WePay',
      Date: '14/1/2001',
      img: '../../defaultProduct.jfif',
      sizes: ['XL', 'L', 'M', 'S'],
      colors: ['#50d71e', '#000000', '#50d71e', '#000000'],
      fullName: 'غيث فيصل عثمان',
      email: 'ghaethoo2001.go@gmail.com',
      number: '+963937082264',
      city: 'حمص',
      Address: ' شارع الحضارة',
    },
    {
      typeOfCustumer: 'غيث عثمان',
      TypeOfProduct: 'كنزة',
      TypeBuy: 'WePay',
      Date: '14/1/2001',
      img: '../../defaultProduct.jfif',
      sizes: ['XL', 'L', 'M', 'S'],
      colors: ['#50d71e', '#000000', '#50d71e', '#000000'],
      fullName: 'غيث فيصل عثمان',
      email: 'ghaethoo2001.go@gmail.com',
      number: '+963937082264',
      city: 'حمص',
      Address: ' شارع الحضارة',
    },
    {
      typeOfCustumer: 'غيث عثمان',
      TypeOfProduct: 'كنزة',
      TypeBuy: 'WePay',
      Date: '14/1/2001',
      img: '../../defaultProduct.jfif',
      sizes: ['XL', 'L', 'M', 'S'],
      colors: ['#50d71e', '#000000', '#50d71e', '#000000'],
      fullName: 'غيث فيصل عثمان',
      email: 'ghaethoo2001.go@gmail.com',
      number: '+963937082264',
      city: 'حمص',
      Address: ' شارع الحضارة',
    },
    {
      typeOfCustumer: 'غيث عثمان',
      TypeOfProduct: 'كنزة',
      TypeBuy: 'WePay',
      Date: '14/1/2001',
      img: '../../defaultProduct.jfif',
      sizes: ['XL', 'L', 'M', 'S'],
      colors: ['#50d71e', '#000000', '#50d71e', '#000000'],
      fullName: 'غيث فيصل عثمان',
      email: 'ghaethoo2001.go@gmail.com',
      number: '+963937082264',
      city: 'حمص',
      Address: ' شارع الحضارة',
    },
    {
      typeOfCustumer: 'غيث عثمان',
      TypeOfProduct: 'كنزة',
      TypeBuy: 'WePay',
      Date: '14/1/2001',
      img: '../../defaultProduct.jfif',
      sizes: ['XL', 'L', 'M', 'S'],
      colors: ['#50d71e', '#000000', '#50d71e', '#000000'],
      fullName: 'غيث فيصل عثمان',
      email: 'ghaethoo2001.go@gmail.com',
      number: '+963937082264',
      city: 'حمص',
      Address: ' شارع الحضارة',
    },
    {
      typeOfCustumer: 'غيث عثمان',
      TypeOfProduct: 'كنزة',
      TypeBuy: 'WePay',
      Date: '14/1/2001',
      img: '../../defaultProduct.jfif',
      sizes: ['XL', 'L', 'M', 'S'],
      colors: ['#50d71e', '#000000', '#50d71e', '#000000'],
      fullName: 'غيث فيصل عثمان',
      email: 'ghaethoo2001.go@gmail.com',
      number: '+963937082264',
      city: 'حمص',
      Address: ' شارع الحضارة',
    },
    {
      typeOfCustumer: 'غيث عثمان',
      TypeOfProduct: 'كنزة',
      TypeBuy: 'WePay',
      Date: '14/1/2001',
      img: '../../defaultProduct.jfif',
      sizes: ['XL', 'L', 'M', 'S'],
      colors: ['#50d71e', '#000000', '#50d71e', '#000000'],
      fullName: 'غيث فيصل عثمان',
      email: 'ghaethoo2001.go@gmail.com',
      number: '+963937082264',
      city: 'حمص',
      Address: ' شارع الحضارة',
    },
    {
      typeOfCustumer: 'غيث عثمان',
      TypeOfProduct: 'كنزة',
      TypeBuy: 'WePay',
      Date: '14/1/2001',
      img: '../../defaultProduct.jfif',
      sizes: ['XL', 'L', 'M', 'S'],
      colors: ['#50d71e', '#000000', '#50d71e', '#000000'],
      fullName: 'غيث فيصل عثمان',
      email: 'ghaethoo2001.go@gmail.com',
      number: '+963937082264',
      city: 'حمص',
      Address: ' شارع الحضارة',
    },
    {
      typeOfCustumer: 'غيث عثمان',
      TypeOfProduct: 'كنزة',
      TypeBuy: 'WePay',
      Date: '14/1/2001',
      img: '../../defaultProduct.jfif',
      sizes: ['XL', 'L', 'M', 'S'],
      colors: ['#50d71e', '#000000', '#50d71e', '#000000'],
      fullName: 'غيث فيصل عثمان',
      email: 'ghaethoo2001.go@gmail.com',
      number: '+963937082264',
      city: 'حمص',
      Address: ' شارع الحضارة',
    },
    {
      typeOfCustumer: 'غيث عثمان',
      TypeOfProduct: 'كنزة',
      TypeBuy: 'WePay',
      Date: '14/1/2001',
      img: '../../defaultProduct.jfif',
      sizes: ['XL', 'L', 'M', 'S'],
      colors: ['#50d71e', '#000000', '#50d71e', '#000000'],
      fullName: 'غيث فيصل عثمان',
      email: 'ghaethoo2001.go@gmail.com',
      number: '+963937082264',
      city: 'حمص',
      Address: ' شارع الحضارة',
    },
    {
      typeOfCustumer: 'غيث عثمان',
      TypeOfProduct: 'كنزة',
      TypeBuy: 'WePay',
      Date: '14/1/2001',
      img: '../../defaultProduct.jfif',
      sizes: ['XL', 'L', 'M', 'S'],
      colors: ['#50d71e', '#000000', '#50d71e', '#000000'],
      fullName: 'غيث فيصل عثمان',
      email: 'ghaethoo2001.go@gmail.com',
      number: '+963937082264',
      city: 'حمص',
      Address: ' شارع الحضارة',
    },
    {
      typeOfCustumer: 'غيث عثمان',
      TypeOfProduct: 'كنزة',
      TypeBuy: 'WePay',
      Date: '14/1/2001',
      img: '../../defaultProduct.jfif',
      sizes: ['XL', 'L', 'M', 'S'],
      colors: ['#50d71e', '#000000', '#50d71e', '#000000'],
      fullName: 'غيث فيصل عثمان',
      email: 'ghaethoo2001.go@gmail.com',
      number: '+963937082264',
      city: 'حمص',
      Address: ' شارع الحضارة',
    },
    {
      typeOfCustumer: 'غيث عثمان',
      TypeOfProduct: 'كنزة',
      TypeBuy: 'WePay',
      Date: '14/1/2001',
      img: '../../defaultProduct.jfif',
      sizes: ['XL', 'L', 'M', 'S'],
      colors: ['#50d71e', '#000000', '#50d71e', '#000000'],
      fullName: 'غيث فيصل عثمان',
      email: 'ghaethoo2001.go@gmail.com',
      number: '+963937082264',
      city: 'حمص',
      Address: ' شارع الحضارة',
    },
    {
      typeOfCustumer: 'غيث عثمان',
      TypeOfProduct: 'كنزة',
      TypeBuy: 'WePay',
      Date: '14/1/2001',
      img: '../../defaultProduct.jfif',
      sizes: ['XL', 'L', 'M', 'S'],
      colors: ['#50d71e', '#000000', '#50d71e', '#000000'],
      fullName: 'غيث فيصل عثمان',
      email: 'ghaethoo2001.go@gmail.com',
      number: '+963937082264',
      city: 'حمص',
      Address: ' شارع الحضارة',
    },
    {
      typeOfCustumer: 'غيث عثمان',
      TypeOfProduct: 'كنزة',
      TypeBuy: 'WePay',
      Date: '14/1/2001',
      img: '../../defaultProduct.jfif',
      sizes: ['XL', 'L', 'M', 'S'],
      colors: ['#50d71e', '#000000', '#50d71e', '#000000'],
      fullName: 'غيث فيصل عثمان',
      email: 'ghaethoo2001.go@gmail.com',
      number: '+963937082264',
      city: 'حمص',
      Address: ' شارع الحضارة',
    },
    {
      typeOfCustumer: 'غيث عثمان',
      TypeOfProduct: 'كنزة',
      TypeBuy: 'WePay',
      Date: '14/1/2001',
      img: '../../defaultProduct.jfif',
      sizes: ['XL', 'L', 'M', 'S'],
      colors: ['#50d71e', '#000000', '#50d71e', '#000000'],
      fullName: 'غيث فيصل عثمان',
      email: 'ghaethoo2001.go@gmail.com',
      number: '+963937082264',
      city: 'حمص',
      Address: ' شارع الحضارة',
    },
    {
      typeOfCustumer: 'غيث عثمان',
      TypeOfProduct: 'كنزة',
      TypeBuy: 'WePay',
      Date: '14/1/2001',
      img: '../../defaultProduct.jfif',
      sizes: ['XL', 'L', 'M', 'S'],
      colors: ['#50d71e', '#000000', '#50d71e', '#000000'],
      fullName: 'غيث فيصل عثمان',
      email: 'ghaethoo2001.go@gmail.com',
      number: '+963937082264',
      city: 'حمص',
      Address: ' شارع الحضارة',
    },
    {
      typeOfCustumer: 'غيث عثمان',
      TypeOfProduct: 'كنزة',
      TypeBuy: 'WePay',
      Date: '14/1/2001',
      img: '../../defaultProduct.jfif',
      sizes: ['XL', 'L', 'M', 'S'],
      colors: ['#50d71e', '#000000', '#50d71e', '#000000'],
      fullName: 'غيث فيصل عثمان',
      email: 'ghaethoo2001.go@gmail.com',
      number: '+963937082264',
      city: 'حمص',
      Address: ' شارع الحضارة',
    },
    {
      typeOfCustumer: 'غيث عثمان',
      TypeOfProduct: 'كنزة',
      TypeBuy: 'WePay',
      Date: '14/1/2001',
      img: '../../defaultProduct.jfif',
      sizes: ['XL', 'L', 'M', 'S'],
      colors: ['#50d71e', '#000000', '#50d71e', '#000000'],
      fullName: 'غيث فيصل عثمان',
      email: 'ghaethoo2001.go@gmail.com',
      number: '+963937082264',
      city: 'حمص',
      Address: ' شارع الحضارة',
    },
    {
      typeOfCustumer: 'غيث عثمان',
      TypeOfProduct: 'كنزة',
      TypeBuy: 'WePay',
      Date: '14/1/2001',
      img: '../../defaultProduct.jfif',
      sizes: ['XL', 'L', 'M', 'S'],
      colors: ['#50d71e', '#000000', '#50d71e', '#000000'],
      fullName: 'غيث فيصل عثمان',
      email: 'ghaethoo2001.go@gmail.com',
      number: '+963937082264',
      city: 'حمص',
      Address: ' شارع الحضارة',
    },
    {
      typeOfCustumer: 'غيث عثمان',
      TypeOfProduct: 'كنزة',
      TypeBuy: 'WePay',
      Date: '14/1/2001',
      img: '../../defaultProduct.jfif',
      sizes: ['XL', 'L', 'M', 'S'],
      colors: ['#50d71e', '#000000', '#50d71e', '#000000'],
      fullName: 'غيث فيصل عثمان',
      email: 'ghaethoo2001.go@gmail.com',
      number: '+963937082264',
      city: 'حمص',
      Address: ' شارع الحضارة',
    },
    {
      typeOfCustumer: 'غيث عثمان',
      TypeOfProduct: 'كنزة',
      TypeBuy: 'WePay',
      Date: '14/1/2001',
      img: '../../defaultProduct.jfif',
      sizes: ['XL', 'L', 'M', 'S'],
      colors: ['#50d71e', '#000000', '#50d71e', '#000000'],
      fullName: 'غيث فيصل عثمان',
      email: 'ghaethoo2001.go@gmail.com',
      number: '+963937082264',
      city: 'حمص',
      Address: ' شارع الحضارة',
    },
    {
      typeOfCustumer: 'غيث عثمان',
      TypeOfProduct: 'كنزة',
      TypeBuy: 'WePay',
      Date: '14/1/2001',
      img: '../../defaultProduct.jfif',
      sizes: ['XL', 'L', 'M', 'S'],
      colors: ['#50d71e', '#000000', '#50d71e', '#000000'],
      fullName: 'غيث فيصل عثمان',
      email: 'ghaethoo2001.go@gmail.com',
      number: '+963937082264',
      city: 'حمص',
      Address: ' شارع الحضارة',
    },
    {
      typeOfCustumer: 'غيث عثمان',
      TypeOfProduct: 'كنزة',
      TypeBuy: 'WePay',
      Date: '14/1/2001',
      img: '../../defaultProduct.jfif',
      sizes: ['XL', 'L', 'M', 'S'],
      colors: ['#50d71e', '#000000', '#50d71e', '#000000'],
      fullName: 'غيث فيصل عثمان',
      email: 'ghaethoo2001.go@gmail.com',
      number: '+963937082264',
      city: 'حمص',
      Address: ' شارع الحضارة',
    },
    {
      typeOfCustumer: 'غيث عثمان',
      TypeOfProduct: 'كنزة',
      TypeBuy: 'WePay',
      Date: '14/1/2001',
      img: '../../defaultProduct.jfif',
      sizes: ['XL', 'L', 'M', 'S'],
      colors: ['#50d71e', '#000000', '#50d71e', '#000000'],
      fullName: 'غيث فيصل عثمان',
      email: 'ghaethoo2001.go@gmail.com',
      number: '+963937082264',
      city: 'حمص',
      Address: ' شارع الحضارة',
    },
    {
      typeOfCustumer: 'غيث عثمان',
      TypeOfProduct: 'كنزة',
      TypeBuy: 'WePay',
      Date: '14/1/2001',
      img: '../../defaultProduct.jfif',
      sizes: ['XL', 'L', 'M', 'S'],
      colors: ['#50d71e', '#000000', '#50d71e', '#000000'],
      fullName: 'غيث فيصل عثمان',
      email: 'ghaethoo2001.go@gmail.com',
      number: '+963937082264',
      city: 'حمص',
      Address: ' شارع الحضارة',
    },
    {
      typeOfCustumer: 'غيث عثمان',
      TypeOfProduct: 'كنزة',
      TypeBuy: 'WePay',
      Date: '14/1/2001',
      img: '../../defaultProduct.jfif',
      sizes: ['XL', 'L', 'M', 'S'],
      colors: ['#50d71e', '#000000', '#50d71e', '#000000'],
      fullName: 'غيث فيصل عثمان',
      email: 'ghaethoo2001.go@gmail.com',
      number: '+963937082264',
      city: 'حمص',
      Address: ' شارع الحضارة',
    },
    {
      typeOfCustumer: 'غيث عثمان',
      TypeOfProduct: 'كنزة',
      TypeBuy: 'WePay',
      Date: '14/1/2001',
      img: '../../defaultProduct.jfif',
      sizes: ['XL', 'L', 'M', 'S'],
      colors: ['#50d71e', '#000000', '#50d71e', '#000000'],
      fullName: 'غيث فيصل عثمان',
      email: 'ghaethoo2001.go@gmail.com',
      number: '+963937082264',
      city: 'حمص',
      Address: ' شارع الحضارة',
    },
    {
      typeOfCustumer: 'غيث عثمان',
      TypeOfProduct: 'كنزة',
      TypeBuy: 'WePay',
      Date: '14/1/2001',
      img: '../../defaultProduct.jfif',
      sizes: ['XL', 'L', 'M', 'S'],
      colors: ['#50d71e', '#000000', '#50d71e', '#000000'],
      fullName: 'غيث فيصل عثمان',
      email: 'ghaethoo2001.go@gmail.com',
      number: '+963937082264',
      city: 'حمص',
      Address: ' شارع الحضارة',
    },
    {
      typeOfCustumer: 'غيث عثمان',
      TypeOfProduct: 'كنزة',
      TypeBuy: 'WePay',
      Date: '14/1/2001',
      img: '../../defaultProduct.jfif',
      sizes: ['XL', 'L', 'M', 'S'],
      colors: ['#50d71e', '#000000', '#50d71e', '#000000'],
      fullName: 'غيث فيصل عثمان',
      email: 'ghaethoo2001.go@gmail.com',
      number: '+963937082264',
      city: 'حمص',
      Address: ' شارع الحضارة',
    },
    {
      typeOfCustumer: 'غيث عثمان',
      TypeOfProduct: 'كنزة',
      TypeBuy: 'WePay',
      Date: '14/1/2001',
      img: '../../defaultProduct.jfif',
      sizes: ['XL', 'L', 'M', 'S'],
      colors: ['#50d71e', '#000000', '#50d71e', '#000000'],
      fullName: 'غيث فيصل عثمان',
      email: 'ghaethoo2001.go@gmail.com',
      number: '+963937082264',
      city: 'حمص',
      Address: ' شارع الحضارة',
    },
    {
      typeOfCustumer: 'غيث عثمان',
      TypeOfProduct: 'كنزة',
      TypeBuy: 'WePay',
      Date: '14/1/2001',
      img: '../../defaultProduct.jfif',
      sizes: ['XL', 'L', 'M', 'S'],
      colors: ['#50d71e', '#000000', '#50d71e', '#000000'],
      fullName: 'غيث فيصل عثمان',
      email: 'ghaethoo2001.go@gmail.com',
      number: '+963937082264',
      city: 'حمص',
      Address: ' شارع الحضارة',
    },
    {
      typeOfCustumer: 'غيث عثمان',
      TypeOfProduct: 'كنزة',
      TypeBuy: 'WePay',
      Date: '14/1/2001',
      img: '../../defaultProduct.jfif',
      sizes: ['XL', 'L', 'M', 'S'],
      colors: ['#50d71e', '#000000', '#50d71e', '#000000'],
      fullName: 'غيث فيصل عثمان',
      email: 'ghaethoo2001.go@gmail.com',
      number: '+963937082264',
      city: 'حمص',
      Address: ' شارع الحضارة',
    },
    {
      typeOfCustumer: 'غيث عثمان',
      TypeOfProduct: 'كنزة',
      TypeBuy: 'WePay',
      Date: '14/1/2001',
      img: '../../defaultProduct.jfif',
      sizes: ['XL', 'L', 'M', 'S'],
      colors: ['#50d71e', '#000000', '#50d71e', '#000000'],
      fullName: 'غيث فيصل عثمان',
      email: 'ghaethoo2001.go@gmail.com',
      number: '+963937082264',
      city: 'حمص',
      Address: ' شارع الحضارة',
    },
    {
      typeOfCustumer: 'غيث عثمان',
      TypeOfProduct: 'كنزة',
      TypeBuy: 'WePay',
      Date: '14/1/2001',
      img: '../../defaultProduct.jfif',
      sizes: ['XL', 'L', 'M', 'S'],
      colors: ['#50d71e', '#000000', '#50d71e', '#000000'],
      fullName: 'غيث فيصل عثمان',
      email: 'ghaethoo2001.go@gmail.com',
      number: '+963937082264',
      city: 'حمص',
      Address: ' شارع الحضارة',
    },
    {
      typeOfCustumer: 'غيث عثمان',
      TypeOfProduct: 'كنزة',
      TypeBuy: 'WePay',
      Date: '14/1/2001',
      img: '../../defaultProduct.jfif',
      sizes: ['XL', 'L', 'M', 'S'],
      colors: ['#50d71e', '#000000', '#50d71e', '#000000'],
      fullName: 'غيث فيصل عثمان',
      email: 'ghaethoo2001.go@gmail.com',
      number: '+963937082264',
      city: 'حمص',
      Address: ' شارع الحضارة',
    },
    {
      typeOfCustumer: 'غيث عثمان',
      TypeOfProduct: 'كنزة',
      TypeBuy: 'WePay',
      Date: '14/1/2001',
      img: '../../defaultProduct.jfif',
      sizes: ['XL', 'L', 'M', 'S'],
      colors: ['#50d71e', '#000000', '#50d71e', '#000000'],
      fullName: 'غيث فيصل عثمان',
      email: 'ghaethoo2001.go@gmail.com',
      number: '+963937082264',
      city: 'حمص',
      Address: ' شارع الحضارة',
    },
    {
      typeOfCustumer: 'غيث عثمان',
      TypeOfProduct: 'كنزة',
      TypeBuy: 'WePay',
      Date: '14/1/2001',
      img: '../../defaultProduct.jfif',
      sizes: ['XL', 'L', 'M', 'S'],
      colors: ['#50d71e', '#000000', '#50d71e', '#000000'],
      fullName: 'غيث فيصل عثمان',
      email: 'ghaethoo2001.go@gmail.com',
      number: '+963937082264',
      city: 'حمص',
      Address: ' شارع الحضارة',
    },
    {
      typeOfCustumer: 'غيث عثمان',
      TypeOfProduct: 'كنزة',
      TypeBuy: 'WePay',
      Date: '14/1/2001',
      img: '../../defaultProduct.jfif',
      sizes: ['XL', 'L', 'M', 'S'],
      colors: ['#50d71e', '#000000', '#50d71e', '#000000'],
      fullName: 'غيث فيصل عثمان',
      email: 'ghaethoo2001.go@gmail.com',
      number: '+963937082264',
      city: 'حمص',
      Address: ' شارع الحضارة',
    },
    {
      typeOfCustumer: 'غيث عثمان',
      TypeOfProduct: 'كنزة',
      TypeBuy: 'WePay',
      Date: '14/1/2001',
      img: '../../defaultProduct.jfif',
      sizes: ['XL', 'L', 'M', 'S'],
      colors: ['#50d71e', '#000000', '#50d71e', '#000000'],
      fullName: 'غيث فيصل عثمان',
      email: 'ghaethoo2001.go@gmail.com',
      number: '+963937082264',
      city: 'حمص',
      Address: ' شارع الحضارة',
    },
    {
      typeOfCustumer: 'غيث عثمان',
      TypeOfProduct: 'كنزة',
      TypeBuy: 'WePay',
      Date: '14/1/2001',
      img: '../../defaultProduct.jfif',
      sizes: ['XL', 'L', 'M', 'S'],
      colors: ['#50d71e', '#000000', '#50d71e', '#000000'],
      fullName: 'غيث فيصل عثمان',
      email: 'ghaethoo2001.go@gmail.com',
      number: '+963937082264',
      city: 'حمص',
      Address: ' شارع الحضارة',
    },
    {
      typeOfCustumer: 'غيث عثمان',
      TypeOfProduct: 'كنزة',
      TypeBuy: 'WePay',
      Date: '14/1/2001',
      img: '../../defaultProduct.jfif',
      sizes: ['XL', 'L', 'M', 'S'],
      colors: ['#50d71e', '#000000', '#50d71e', '#000000'],
      fullName: 'غيث فيصل عثمان',
      email: 'ghaethoo2001.go@gmail.com',
      number: '+963937082264',
      city: 'حمص',
      Address: ' شارع الحضارة',
    },
    {
      typeOfCustumer: 'غيث عثمان',
      TypeOfProduct: 'كنزة',
      TypeBuy: 'WePay',
      Date: '14/1/2001',
      img: '../../defaultProduct.jfif',
      sizes: ['XL', 'L', 'M', 'S'],
      colors: ['#50d71e', '#000000', '#50d71e', '#000000'],
      fullName: 'غيث فيصل عثمان',
      email: 'ghaethoo2001.go@gmail.com',
      number: '+963937082264',
      city: 'حمص',
      Address: ' شارع الحضارة',
    },
    {
      typeOfCustumer: 'غيث عثمان',
      TypeOfProduct: 'كنزة',
      TypeBuy: 'WePay',
      Date: '14/1/2001',
      img: '../../defaultProduct.jfif',
      sizes: ['XL', 'L', 'M', 'S'],
      colors: ['#50d71e', '#000000', '#50d71e', '#000000'],
      fullName: 'غيث فيصل عثمان',
      email: 'ghaethoo2001.go@gmail.com',
      number: '+963937082264',
      city: 'حمص',
      Address: ' شارع الحضارة',
    },
    {
      typeOfCustumer: 'رونيا عودة',
      TypeOfProduct: 'كنزة',
      TypeBuy: 'WePay',
      Date: '14/1/2001',
      img: '../../defaultProduct.jfif',
      sizes: ['XL', 'L', 'M', 'S'],
      colors: ['#50d71e', '#000000', '#50d71e', '#000000'],
      fullName: 'غيث فيصل عثمان',
      email: 'ghaethoo2001.go@gmail.com',
      number: '+963937082264',
      city: 'حمص',
      Address: ' شارع الحضارة',
    },
    {
      typeOfCustumer: 'علي الديوب',
      TypeOfProduct: 'كنزة',
      TypeBuy: 'WePay',
      Date: '14/1/2001',
      img: '../../defaultProduct.jfif',
      sizes: ['XL', 'L', 'M', 'S'],
      colors: ['#50d71e', '#000000', '#50d71e', '#000000'],
      fullName: 'غيث فيصل عثمان',
      email: 'ghaethoo2001.go@gmail.com',
      number: '+963937082264',
      city: 'حمص',
      Address: ' شارع الحضارة',
    },
    {
      typeOfCustumer: 'ماريلا رحال',
      TypeOfProduct: 'كنزة',
      TypeBuy: 'WePay',
      Date: '14/1/2001',
      img: '../../defaultProduct.jfif',
      sizes: ['XL', 'L', 'M', 'S'],
      colors: ['#50d71e', '#000000', '#50d71e', '#000000'],
      fullName: 'غيث فيصل عثمان',
      email: 'ghaethoo2001.go@gmail.com',
      number: '+963937082264',
      city: 'حمص',
      Address: ' شارع الحضارة',
    },
    {
      typeOfCustumer: 'حسن المحمود',
      TypeOfProduct: 'كنزة',
      TypeBuy: 'WePay',
      Date: '14/1/2001',
      img: '../../defaultProduct.jfif',
      sizes: ['XL', 'L', 'M', 'S'],
      colors: ['#50d71e', '#000000', '#50d71e', '#000000'],
      fullName: 'غيث فيصل عثمان',
      email: 'ghaethoo2001.go@gmail.com',
      number: '+963937082264',
      city: 'حمص',
      Address: ' شارع الحضارة',
    },
    {
      typeOfCustumer: 'أحمد أحمد',
      TypeOfProduct: 'كنزة',
      TypeBuy: 'WePay',
      Date: '14/1/2001',
      img: '../../defaultProduct.jfif',
      sizes: ['XL', 'L', 'M', 'S'],
      colors: ['#50d71e', '#000000', '#50d71e', '#000000'],
      fullName: 'غيث فيصل عثمان',
      email: 'ghaethoo2001.go@gmail.com',
      number: '+963937082264',
      city: 'حمص',
      Address: ' شارع الحضارة',
    },
    {
      typeOfCustumer: 'علاء أحمد',
      TypeOfProduct: 'كنزة',
      TypeBuy: 'WePay',
      Date: '14/1/2001',
      img: '../../defaultProduct.jfif',
      sizes: ['XL', 'L', 'M', 'S'],
      colors: ['#50d71e', '#000000', '#50d71e', '#000000'],
      fullName: 'غيث فيصل عثمان',
      email: 'ghaethoo2001.go@gmail.com',
      number: '+963937082264',
      city: 'حمص',
      Address: ' شارع الحضارة',
    },
    {
      typeOfCustumer: 'ماريلا رحال',
      TypeOfProduct: 'كنزة',
      TypeBuy: 'WePay',
      Date: '14/1/2001',
      img: '../../defaultProduct.jfif',
      sizes: ['XL', 'L', 'M', 'S'],
      colors: ['#50d71e', '#000000', '#50d71e', '#000000'],
      fullName: 'غيث فيصل عثمان',
      email: 'ghaethoo2001.go@gmail.com',
      number: '+963937082264',
      city: 'حمص',
      Address: ' شارع الحضارة',
    },
    {
      typeOfCustumer: 'غيث عثمان',
      TypeOfProduct: 'كنزة',
      TypeBuy: 'WePay',
      Date: '14/1/2001',
      img: '../../defaultProduct.jfif',
      sizes: ['XL', 'L', 'M', 'S'],
      colors: ['#50d71e', '#000000', '#50d71e', '#000000'],
      fullName: 'غيث فيصل عثمان',
      email: 'ghaethoo2001.go@gmail.com',
      number: '+963937082264',
      city: 'حمص',
      Address: ' شارع الحضارة',
    },
    {
      typeOfCustumer: 'رونيا عودة',
      TypeOfProduct: 'كنزة',
      TypeBuy: 'WePay',
      Date: '14/1/2001',
      img: '../../defaultProduct.jfif',
      sizes: ['XL', 'L', 'M', 'S'],
      colors: ['#50d71e', '#000000', '#50d71e', '#000000'],
      fullName: 'غيث فيصل عثمان',
      email: 'ghaethoo2001.go@gmail.com',
      number: '+963937082264',
      city: 'حمص',
      Address: ' شارع الحضارة',
    },
    {
      typeOfCustumer: 'علي الديوب',
      TypeOfProduct: 'كنزة',
      TypeBuy: 'WePay',
      Date: '14/1/2001',
      img: '../../defaultProduct.jfif',
      sizes: ['XL', 'L', 'M', 'S'],
      colors: ['#50d71e', '#000000', '#50d71e', '#000000'],
      fullName: 'غيث فيصل عثمان',
      email: 'ghaethoo2001.go@gmail.com',
      number: '+963937082264',
      city: 'حمص',
      Address: ' شارع الحضارة',
    },
    {
      typeOfCustumer: 'ماريلا رحال',
      TypeOfProduct: 'كنزة',
      TypeBuy: 'WePay',
      Date: '14/1/2001',
      img: '../../defaultProduct.jfif',
      sizes: ['XL', 'L', 'M', 'S'],
      colors: ['#50d71e', '#000000', '#50d71e', '#000000'],
      fullName: 'غيث فيصل عثمان',
      email: 'ghaethoo2001.go@gmail.com',
      number: '+963937082264',
      city: 'حمص',
      Address: ' شارع الحضارة',
    },
    {
      typeOfCustumer: 'غيث عثمان',
      TypeOfProduct: 'كنزة',
      TypeBuy: 'WePay',
      Date: '14/1/2001',
      img: '../../defaultProduct.jfif',
      sizes: ['XL', 'L', 'M', 'S'],
      colors: ['#50d71e', '#000000', '#50d71e', '#000000'],
      fullName: 'غيث فيصل عثمان',
      email: 'ghaethoo2001.go@gmail.com',
      number: '+963937082264',
      city: 'حمص',
      Address: ' شارع الحضارة',
    },
    {
      typeOfCustumer: 'رونيا عودة',
      TypeOfProduct: 'كنزة',
      TypeBuy: 'WePay',
      Date: '14/1/2001',
      img: '../../defaultProduct.jfif',
      sizes: ['XL', 'L', 'M', 'S'],
      colors: ['#50d71e', '#000000', '#50d71e', '#000000'],
      fullName: 'غيث فيصل عثمان',
      email: 'ghaethoo2001.go@gmail.com',
      number: '+963937082264',
      city: 'حمص',
      Address: ' شارع الحضارة',
    },
    {
      typeOfCustumer: 'علي الديوب',
      TypeOfProduct: 'كنزة',
      TypeBuy: 'WePay',
      Date: '14/1/2001',
      img: '../../defaultProduct.jfif',
      sizes: ['XL', 'L', 'M', 'S'],
      colors: ['#50d71e', '#000000', '#50d71e', '#000000'],
      fullName: 'غيث فيصل عثمان',
      email: 'ghaethoo2001.go@gmail.com',
      number: '+963937082264',
      city: 'حمص',
      Address: ' شارع الحضارة',
    },
    {
      typeOfCustumer: 'ماريلا رحال',
      TypeOfProduct: 'كنزة',
      TypeBuy: 'WePay',
      Date: '14/1/2001',
      img: '../../defaultProduct.jfif',
      sizes: ['XL', 'L', 'M', 'S'],
      colors: ['#50d71e', '#000000', '#50d71e', '#000000'],
      fullName: 'غيث فيصل عثمان',
      email: 'ghaethoo2001.go@gmail.com',
      number: '+963937082264',
      city: 'حمص',
      Address: ' شارع الحضارة',
    },
    {
      typeOfCustumer: 'غيث عثمان',
      TypeOfProduct: 'كنزة',
      TypeBuy: 'WePay',
      Date: '14/1/2001',
      img: '../../defaultProduct.jfif',
      sizes: ['XL', 'L', 'M', 'S'],
      colors: ['#50d71e', '#000000', '#50d71e', '#000000'],
      fullName: 'غيث فيصل عثمان',
      email: 'ghaethoo2001.go@gmail.com',
      number: '+963937082264',
      city: 'حمص',
      Address: ' شارع الحضارة',
    },
    {
      typeOfCustumer: 'رونيا عودة',
      TypeOfProduct: 'كنزة',
      TypeBuy: 'WePay',
      Date: '14/1/2001',
      img: '../../defaultProduct.jfif',
      sizes: ['XL', 'L', 'M', 'S'],
      colors: ['#50d71e', '#000000', '#50d71e', '#000000'],
      fullName: 'غيث فيصل عثمان',
      email: 'ghaethoo2001.go@gmail.com',
      number: '+963937082264',
      city: 'حمص',
      Address: ' شارع الحضارة',
    },
    {
      typeOfCustumer: 'علي الديوب',
      TypeOfProduct: 'كنزة',
      TypeBuy: 'WePay',
      Date: '14/1/2001',
      img: '../../defaultProduct.jfif',
      sizes: ['XL', 'L', 'M', 'S'],
      colors: ['#50d71e', '#000000', '#50d71e', '#000000'],
      fullName: 'غيث فيصل عثمان',
      email: 'ghaethoo2001.go@gmail.com',
      number: '+963937082264',
      city: 'حمص',
      Address: ' شارع الحضارة',
    },
    {
      typeOfCustumer: 'ماريلا رحال',
      TypeOfProduct: 'كنزة',
      TypeBuy: 'WePay',
      Date: '14/1/2001',
      img: '../../defaultProduct.jfif',
      sizes: ['XL', 'L', 'M', 'S'],
      colors: ['#50d71e', '#000000', '#50d71e', '#000000'],
      fullName: 'غيث فيصل عثمان',
      email: 'ghaethoo2001.go@gmail.com',
      number: '+963937082264',
      city: 'حمص',
      Address: ' شارع الحضارة',
    },
    {
      typeOfCustumer: 'ماريلا رحال',
      TypeOfProduct: 'كنزة',
      TypeBuy: 'WePay',
      Date: '14/1/2001',
      img: '../../defaultProduct.jfif',
      sizes: ['XL', 'L', 'M', 'S'],
      colors: ['#50d71e', '#000000', '#50d71e', '#000000'],
      fullName: 'غيث فيصل عثمان',
      email: 'ghaethoo2001.go@gmail.com',
      number: '+963937082264',
      city: 'حمص',
      Address: ' شارع الحضارة',
    },
    {
      typeOfCustumer: 'غيث عثمان',
      TypeOfProduct: 'كنزة',
      TypeBuy: 'WePay',
      Date: '14/1/2001',
      img: '../../defaultProduct.jfif',
      sizes: ['XL', 'L', 'M', 'S'],
      colors: ['#50d71e', '#000000', '#50d71e', '#000000'],
      fullName: 'غيث فيصل عثمان',
      email: 'ghaethoo2001.go@gmail.com',
      number: '+963937082264',
      city: 'حمص',
      Address: ' شارع الحضارة',
    },
    {
      typeOfCustumer: 'رونيا عودة',
      TypeOfProduct: 'كنزة',
      TypeBuy: 'WePay',
      Date: '14/1/2001',
      img: '../../defaultProduct.jfif',
      sizes: ['XL', 'L', 'M', 'S'],
      colors: ['#50d71e', '#000000', '#50d71e', '#000000'],
      fullName: 'غيث فيصل عثمان',
      email: 'ghaethoo2001.go@gmail.com',
      number: '+963937082264',
      city: 'حمص',
      Address: ' شارع الحضارة',
    },
    {
      typeOfCustumer: 'علي الديوب',
      TypeOfProduct: 'كنزة',
      TypeBuy: 'WePay',
      Date: '14/1/2001',
      img: '../../defaultProduct.jfif',
      sizes: ['XL', 'L', 'M', 'S'],
      colors: ['#50d71e', '#000000', '#50d71e', '#000000'],
      fullName: 'غيث فيصل عثمان',
      email: 'ghaethoo2001.go@gmail.com',
      number: '+963937082264',
      city: 'حمص',
      Address: ' شارع الحضارة',
    },
    {
      typeOfCustumer: 'ماريلا رحال',
      TypeOfProduct: 'كنزة',
      TypeBuy: 'WePay',
      Date: '14/1/2001',
      img: '../../defaultProduct.jfif',
      sizes: ['XL', 'L', 'M', 'S'],
      colors: ['#50d71e', '#000000', '#50d71e', '#000000'],
      fullName: 'غيث فيصل عثمان',
      email: 'ghaethoo2001.go@gmail.com',
      number: '+963937082264',
      city: 'حمص',
      Address: ' شارع الحضارة',
    },
    {
      typeOfCustumer: 'حسن المحمود',
      TypeOfProduct: 'كنزة',
      TypeBuy: 'WePay',
      Date: '14/1/2001',
      img: '../../defaultProduct.jfif',
      sizes: ['XL', 'L', 'M', 'S'],
      colors: ['#50d71e', '#000000', '#50d71e', '#000000'],
      fullName: 'غيث فيصل عثمان',
      email: 'ghaethoo2001.go@gmail.com',
      number: '+963937082264',
      city: 'حمص',
      Address: ' شارع الحضارة',
    },
    {
      typeOfCustumer: 'أحمد أحمد',
      TypeOfProduct: 'كنزة',
      TypeBuy: 'WePay',
      Date: '14/1/2001',
      img: '../../defaultProduct.jfif',
      sizes: ['XL', 'L', 'M', 'S'],
      colors: ['#50d71e', '#000000', '#50d71e', '#000000'],
      fullName: 'غيث فيصل عثمان',
      email: 'ghaethoo2001.go@gmail.com',
      number: '+963937082264',
      city: 'حمص',
      Address: ' شارع الحضارة',
    },
    {
      typeOfCustumer: 'علاء أحمد',
      TypeOfProduct: 'كنزة',
      TypeBuy: 'WePay',
      Date: '14/1/2001',
      img: '../../defaultProduct.jfif',
      sizes: ['XL', 'L', 'M', 'S'],
      colors: ['#50d71e', '#000000', '#50d71e', '#000000'],
      fullName: 'غيث فيصل عثمان',
      email: 'ghaethoo2001.go@gmail.com',
      number: '+963937082264',
      city: 'حمص',
      Address: ' شارع الحضارة',
    },
    {
      typeOfCustumer: 'ماريلا رحال',
      TypeOfProduct: 'كنزة',
      TypeBuy: 'WePay',
      Date: '14/1/2001',
      img: '../../defaultProduct.jfif',
      sizes: ['XL', 'L', 'M', 'S'],
      colors: ['#50d71e', '#000000', '#50d71e', '#000000'],
      fullName: 'غيث فيصل عثمان',
      email: 'ghaethoo2001.go@gmail.com',
      number: '+963937082264',
      city: 'حمص',
      Address: ' شارع الحضارة',
    },
    {
      typeOfCustumer: 'غيث عثمان',
      TypeOfProduct: 'كنزة',
      TypeBuy: 'WePay',
      Date: '14/1/2001',
      img: '../../defaultProduct.jfif',
      sizes: ['XL', 'L', 'M', 'S'],
      colors: ['#50d71e', '#000000', '#50d71e', '#000000'],
      fullName: 'غيث فيصل عثمان',
      email: 'ghaethoo2001.go@gmail.com',
      number: '+963937082264',
      city: 'حمص',
      Address: ' شارع الحضارة',
    },
    {
      typeOfCustumer: 'رونيا عودة',
      TypeOfProduct: 'كنزة',
      TypeBuy: 'WePay',
      Date: '14/1/2001',
      img: '../../defaultProduct.jfif',
      sizes: ['XL', 'L', 'M', 'S'],
      colors: ['#50d71e', '#000000', '#50d71e', '#000000'],
      fullName: 'غيث فيصل عثمان',
      email: 'ghaethoo2001.go@gmail.com',
      number: '+963937082264',
      city: 'حمص',
      Address: ' شارع الحضارة',
    },
    {
      typeOfCustumer: 'علي الديوب',
      TypeOfProduct: 'كنزة',
      TypeBuy: 'WePay',
      Date: '14/1/2001',
      img: '../../defaultProduct.jfif',
      sizes: ['XL', 'L', 'M', 'S'],
      colors: ['#50d71e', '#000000', '#50d71e', '#000000'],
      fullName: 'غيث فيصل عثمان',
      email: 'ghaethoo2001.go@gmail.com',
      number: '+963937082264',
      city: 'حمص',
      Address: ' شارع الحضارة',
    },
    {
      typeOfCustumer: 'ماريلا رحال',
      TypeOfProduct: 'كنزة',
      TypeBuy: 'WePay',
      Date: '14/1/2001',
      img: '../../defaultProduct.jfif',
      sizes: ['XL', 'L', 'M', 'S'],
      colors: ['#50d71e', '#000000', '#50d71e', '#000000'],
      fullName: 'غيث فيصل عثمان',
      email: 'ghaethoo2001.go@gmail.com',
      number: '+963937082264',
      city: 'حمص',
      Address: ' شارع الحضارة',
    },
    {
      typeOfCustumer: 'غيث عثمان',
      TypeOfProduct: 'كنزة',
      TypeBuy: 'WePay',
      Date: '14/1/2001',
      img: '../../defaultProduct.jfif',
      sizes: ['XL', 'L', 'M', 'S'],
      colors: ['#50d71e', '#000000', '#50d71e', '#000000'],
      fullName: 'غيث فيصل عثمان',
      email: 'ghaethoo2001.go@gmail.com',
      number: '+963937082264',
      city: 'حمص',
      Address: ' شارع الحضارة',
    },
    {
      typeOfCustumer: 'رونيا عودة',
      TypeOfProduct: 'كنزة',
      TypeBuy: 'WePay',
      Date: '14/1/2001',
      img: '../../defaultProduct.jfif',
      sizes: ['XL', 'L', 'M', 'S'],
      colors: ['#50d71e', '#000000', '#50d71e', '#000000'],
      fullName: 'غيث فيصل عثمان',
      email: 'ghaethoo2001.go@gmail.com',
      number: '+963937082264',
      city: 'حمص',
      Address: ' شارع الحضارة',
    },
    {
      typeOfCustumer: 'علي الديوب',
      TypeOfProduct: 'كنزة',
      TypeBuy: 'WePay',
      Date: '14/1/2001',
      img: '../../defaultProduct.jfif',
      sizes: ['XL', 'L', 'M', 'S'],
      colors: ['#50d71e', '#000000', '#50d71e', '#000000'],
      fullName: 'غيث فيصل عثمان',
      email: 'ghaethoo2001.go@gmail.com',
      number: '+963937082264',
      city: 'حمص',
      Address: ' شارع الحضارة',
    },
    {
      typeOfCustumer: 'ماريلا رحال',
      TypeOfProduct: 'كنزة',
      TypeBuy: 'WePay',
      Date: '14/1/2001',
      img: '../../defaultProduct.jfif',
      sizes: ['XL', 'L', 'M', 'S'],
      colors: ['#50d71e', '#000000', '#50d71e', '#000000'],
      fullName: 'غيث فيصل عثمان',
      email: 'ghaethoo2001.go@gmail.com',
      number: '+963937082264',
      city: 'حمص',
      Address: ' شارع الحضارة',
    },
    {
      typeOfCustumer: 'غيث عثمان',
      TypeOfProduct: 'كنزة',
      TypeBuy: 'WePay',
      Date: '14/1/2001',
      img: '../../defaultProduct.jfif',
      sizes: ['XL', 'L', 'M', 'S'],
      colors: ['#50d71e', '#000000', '#50d71e', '#000000'],
      fullName: 'غيث فيصل عثمان',
      email: 'ghaethoo2001.go@gmail.com',
      number: '+963937082264',
      city: 'حمص',
      Address: ' شارع الحضارة',
    },
    {
      typeOfCustumer: 'رونيا عودة',
      TypeOfProduct: 'كنزة',
      TypeBuy: 'WePay',
      Date: '14/1/2001',
      img: '../../defaultProduct.jfif',
      sizes: ['XL', 'L', 'M', 'S'],
      colors: ['#50d71e', '#000000', '#50d71e', '#000000'],
      fullName: 'غيث فيصل عثمان',
      email: 'ghaethoo2001.go@gmail.com',
      number: '+963937082264',
      city: 'حمص',
      Address: ' شارع الحضارة',
    },
    {
      typeOfCustumer: 'علي الديوب',
      TypeOfProduct: 'كنزة',
      TypeBuy: 'WePay',
      Date: '14/1/2001',
      img: '../../defaultProduct.jfif',
      sizes: ['XL', 'L', 'M', 'S'],
      colors: ['#50d71e', '#000000', '#50d71e', '#000000'],
      fullName: 'غيث فيصل عثمان',
      email: 'ghaethoo2001.go@gmail.com',
      number: '+963937082264',
      city: 'حمص',
      Address: ' شارع الحضارة',
    },
    {
      typeOfCustumer: 'ماريلا رحال',
      TypeOfProduct: 'كنزة',
      TypeBuy: 'WePay',
      Date: '14/1/2001',
      img: '../../defaultProduct.jfif',
      sizes: ['XL', 'L', 'M', 'S'],
      colors: ['#50d71e', '#000000', '#50d71e', '#000000'],
      fullName: 'غيث فيصل عثمان',
      email: 'ghaethoo2001.go@gmail.com',
      number: '+963937082264',
      city: 'حمص',
      Address: ' شارع الحضارة',
    },
    {
      typeOfCustumer: 'ماريلا رحال',
      TypeOfProduct: 'كنزة',
      TypeBuy: 'WePay',
      Date: '14/1/2001',
      img: '../../defaultProduct.jfif',
      sizes: ['XL', 'L', 'M', 'S'],
      colors: ['#50d71e', '#000000', '#50d71e', '#000000'],
      fullName: 'غيث فيصل عثمان',
      email: 'ghaethoo2001.go@gmail.com',
      number: '+963937082264',
      city: 'حمص',
      Address: ' شارع الحضارة',
    },
    {
      typeOfCustumer: 'غيث عثمان',
      TypeOfProduct: 'كنزة',
      TypeBuy: 'WePay',
      Date: '14/1/2001',
      img: '../../defaultProduct.jfif',
      sizes: ['XL', 'L', 'M', 'S'],
      colors: ['#50d71e', '#000000', '#50d71e', '#000000'],
      fullName: 'غيث فيصل عثمان',
      email: 'ghaethoo2001.go@gmail.com',
      number: '+963937082264',
      city: 'حمص',
      Address: ' شارع الحضارة',
    },
    {
      typeOfCustumer: 'رونيا عودة',
      TypeOfProduct: 'كنزة',
      TypeBuy: 'WePay',
      Date: '14/1/2001',
      img: '../../defaultProduct.jfif',
      sizes: ['XL', 'L', 'M', 'S'],
      colors: ['#50d71e', '#000000', '#50d71e', '#000000'],
      fullName: 'غيث فيصل عثمان',
      email: 'ghaethoo2001.go@gmail.com',
      number: '+963937082264',
      city: 'حمص',
      Address: ' شارع الحضارة',
    },
    {
      typeOfCustumer: 'علي الديوب',
      TypeOfProduct: 'كنزة',
      TypeBuy: 'WePay',
      Date: '14/1/2001',
      img: '../../defaultProduct.jfif',
      sizes: ['XL', 'L', 'M', 'S'],
      colors: ['#50d71e', '#000000', '#50d71e', '#000000'],
      fullName: 'غيث فيصل عثمان',
      email: 'ghaethoo2001.go@gmail.com',
      number: '+963937082264',
      city: 'حمص',
      Address: ' شارع الحضارة',
    },
    {
      typeOfCustumer: 'ماريلا رحال',
      TypeOfProduct: 'كنزة',
      TypeBuy: 'WePay',
      Date: '14/1/2001',
      img: '../../defaultProduct.jfif',
      sizes: ['XL', 'L', 'M', 'S'],
      colors: ['#50d71e', '#000000', '#50d71e', '#000000'],
      fullName: 'غيث فيصل عثمان',
      email: 'ghaethoo2001.go@gmail.com',
      number: '+963937082264',
      city: 'حمص',
      Address: ' شارع الحضارة',
    },
    {
      typeOfCustumer: 'حسن المحمود',
      TypeOfProduct: 'كنزة',
      TypeBuy: 'WePay',
      Date: '14/1/2001',
      img: '../../defaultProduct.jfif',
      sizes: ['XL', 'L', 'M', 'S'],
      colors: ['#50d71e', '#000000', '#50d71e', '#000000'],
      fullName: 'غيث فيصل عثمان',
      email: 'ghaethoo2001.go@gmail.com',
      number: '+963937082264',
      city: 'حمص',
      Address: ' شارع الحضارة',
    },
    {
      typeOfCustumer: 'أحمد أحمد',
      TypeOfProduct: 'كنزة',
      TypeBuy: 'WePay',
      Date: '14/1/2001',
      img: '../../defaultProduct.jfif',
      sizes: ['XL', 'L', 'M', 'S'],
      colors: ['#50d71e', '#000000', '#50d71e', '#000000'],
      fullName: 'غيث فيصل عثمان',
      email: 'ghaethoo2001.go@gmail.com',
      number: '+963937082264',
      city: 'حمص',
      Address: ' شارع الحضارة',
    },
    {
      typeOfCustumer: 'علاء أحمد',
      TypeOfProduct: 'كنزة',
      TypeBuy: 'WePay',
      Date: '14/1/2001',
      img: '../../defaultProduct.jfif',
      sizes: ['XL', 'L', 'M', 'S'],
      colors: ['#50d71e', '#000000', '#50d71e', '#000000'],
      fullName: 'غيث فيصل عثمان',
      email: 'ghaethoo2001.go@gmail.com',
      number: '+963937082264',
      city: 'حمص',
      Address: ' شارع الحضارة',
    },
    {
      typeOfCustumer: 'ماريلا رحال',
      TypeOfProduct: 'كنزة',
      TypeBuy: 'WePay',
      Date: '14/1/2001',
      img: '../../defaultProduct.jfif',
      sizes: ['XL', 'L', 'M', 'S'],
      colors: ['#50d71e', '#000000', '#50d71e', '#000000'],
      fullName: 'غيث فيصل عثمان',
      email: 'ghaethoo2001.go@gmail.com',
      number: '+963937082264',
      city: 'حمص',
      Address: ' شارع الحضارة',
    },
    {
      typeOfCustumer: 'غيث عثمان',
      TypeOfProduct: 'كنزة',
      TypeBuy: 'WePay',
      Date: '14/1/2001',
      img: '../../defaultProduct.jfif',
      sizes: ['XL', 'L', 'M', 'S'],
      colors: ['#50d71e', '#000000', '#50d71e', '#000000'],
      fullName: 'غيث فيصل عثمان',
      email: 'ghaethoo2001.go@gmail.com',
      number: '+963937082264',
      city: 'حمص',
      Address: ' شارع الحضارة',
    },
    {
      typeOfCustumer: 'رونيا عودة',
      TypeOfProduct: 'كنزة',
      TypeBuy: 'WePay',
      Date: '14/1/2001',
      img: '../../defaultProduct.jfif',
      sizes: ['XL', 'L', 'M', 'S'],
      colors: ['#50d71e', '#000000', '#50d71e', '#000000'],
      fullName: 'غيث فيصل عثمان',
      email: 'ghaethoo2001.go@gmail.com',
      number: '+963937082264',
      city: 'حمص',
      Address: ' شارع الحضارة',
    },
    {
      typeOfCustumer: 'علي الديوب',
      TypeOfProduct: 'كنزة',
      TypeBuy: 'WePay',
      Date: '14/1/2001',
      img: '../../defaultProduct.jfif',
      sizes: ['XL', 'L', 'M', 'S'],
      colors: ['#50d71e', '#000000', '#50d71e', '#000000'],
      fullName: 'غيث فيصل عثمان',
      email: 'ghaethoo2001.go@gmail.com',
      number: '+963937082264',
      city: 'حمص',
      Address: ' شارع الحضارة',
    },
    {
      typeOfCustumer: 'ماريلا رحال',
      TypeOfProduct: 'كنزة',
      TypeBuy: 'WePay',
      Date: '14/1/2001',
      img: '../../defaultProduct.jfif',
      sizes: ['XL', 'L', 'M', 'S'],
      colors: ['#50d71e', '#000000', '#50d71e', '#000000'],
      fullName: 'غيث فيصل عثمان',
      email: 'ghaethoo2001.go@gmail.com',
      number: '+963937082264',
      city: 'حمص',
      Address: ' شارع الحضارة',
    },
    {
      typeOfCustumer: 'غيث عثمان',
      TypeOfProduct: 'كنزة',
      TypeBuy: 'WePay',
      Date: '14/1/2001',
      img: '../../defaultProduct.jfif',
      sizes: ['XL', 'L', 'M', 'S'],
      colors: ['#50d71e', '#000000', '#50d71e', '#000000'],
      fullName: 'غيث فيصل عثمان',
      email: 'ghaethoo2001.go@gmail.com',
      number: '+963937082264',
      city: 'حمص',
      Address: ' شارع الحضارة',
    },
    {
      typeOfCustumer: 'رونيا عودة',
      TypeOfProduct: 'كنزة',
      TypeBuy: 'WePay',
      Date: '14/1/2001',
      img: '../../defaultProduct.jfif',
      sizes: ['XL', 'L', 'M', 'S'],
      colors: ['#50d71e', '#000000', '#50d71e', '#000000'],
      fullName: 'غيث فيصل عثمان',
      email: 'ghaethoo2001.go@gmail.com',
      number: '+963937082264',
      city: 'حمص',
      Address: ' شارع الحضارة',
    },
    {
      typeOfCustumer: 'علي الديوب',
      TypeOfProduct: 'كنزة',
      TypeBuy: 'WePay',
      Date: '14/1/2001',
      img: '../../defaultProduct.jfif',
      sizes: ['XL', 'L', 'M', 'S'],
      colors: ['#50d71e', '#000000', '#50d71e', '#000000'],
      fullName: 'غيث فيصل عثمان',
      email: 'ghaethoo2001.go@gmail.com',
      number: '+963937082264',
      city: 'حمص',
      Address: ' شارع الحضارة',
    },
    {
      typeOfCustumer: 'ماريلا رحال',
      TypeOfProduct: 'كنزة',
      TypeBuy: 'WePay',
      Date: '14/1/2001',
      img: '../../defaultProduct.jfif',
      sizes: ['XL', 'L', 'M', 'S'],
      colors: ['#50d71e', '#000000', '#50d71e', '#000000'],
      fullName: 'غيث فيصل عثمان',
      email: 'ghaethoo2001.go@gmail.com',
      number: '+963937082264',
      city: 'حمص',
      Address: ' شارع الحضارة',
    },
    {
      typeOfCustumer: 'غيث عثمان',
      TypeOfProduct: 'كنزة',
      TypeBuy: 'WePay',
      Date: '14/1/2001',
      img: '../../defaultProduct.jfif',
      sizes: ['XL', 'L', 'M', 'S'],
      colors: ['#50d71e', '#000000', '#50d71e', '#000000'],
      fullName: 'غيث فيصل عثمان',
      email: 'ghaethoo2001.go@gmail.com',
      number: '+963937082264',
      city: 'حمص',
      Address: ' شارع الحضارة',
    },
    {
      typeOfCustumer: 'رونيا عودة',
      TypeOfProduct: 'كنزة',
      TypeBuy: 'WePay',
      Date: '14/1/2001',
      img: '../../defaultProduct.jfif',
      sizes: ['XL', 'L', 'M', 'S'],
      colors: ['#50d71e', '#000000', '#50d71e', '#000000'],
      fullName: 'غيث فيصل عثمان',
      email: 'ghaethoo2001.go@gmail.com',
      number: '+963937082264',
      city: 'حمص',
      Address: ' شارع الحضارة',
    },
    {
      typeOfCustumer: 'علي الديوب',
      TypeOfProduct: 'كنزة',
      TypeBuy: 'WePay',
      Date: '14/1/2001',
      img: '../../defaultProduct.jfif',
      sizes: ['XL', 'L', 'M', 'S'],
      colors: ['#50d71e', '#000000', '#50d71e', '#000000'],
      fullName: 'غيث فيصل عثمان',
      email: 'ghaethoo2001.go@gmail.com',
      number: '+963937082264',
      city: 'حمص',
      Address: ' شارع الحضارة',
    },
    {
      typeOfCustumer: 'ماريلا رحال',
      TypeOfProduct: 'كنزة',
      TypeBuy: 'WePay',
      Date: '14/1/2001',
      img: '../../defaultProduct.jfif',
      sizes: ['XL', 'L', 'M', 'S'],
      colors: ['#50d71e', '#000000', '#50d71e', '#000000'],
      fullName: 'غيث فيصل عثمان',
      email: 'ghaethoo2001.go@gmail.com',
      number: '+963937082264',
      city: 'حمص',
      Address: ' شارع الحضارة',
    },
    {
      typeOfCustumer: 'ماريلا رحال',
      TypeOfProduct: 'كنزة',
      TypeBuy: 'WePay',
      Date: '14/1/2001',
      img: '../../defaultProduct.jfif',
      sizes: ['XL', 'L', 'M', 'S'],
      colors: ['#50d71e', '#000000', '#50d71e', '#000000'],
      fullName: 'غيث فيصل عثمان',
      email: 'ghaethoo2001.go@gmail.com',
      number: '+963937082264',
      city: 'حمص',
      Address: ' شارع الحضارة',
    },
    {
      typeOfCustumer: 'غيث عثمان',
      TypeOfProduct: 'كنزة',
      TypeBuy: 'WePay',
      Date: '14/1/2001',
      img: '../../defaultProduct.jfif',
      sizes: ['XL', 'L', 'M', 'S'],
      colors: ['#50d71e', '#000000', '#50d71e', '#000000'],
      fullName: 'غيث فيصل عثمان',
      email: 'ghaethoo2001.go@gmail.com',
      number: '+963937082264',
      city: 'حمص',
      Address: ' شارع الحضارة',
    },
    {
      typeOfCustumer: 'رونيا عودة',
      TypeOfProduct: 'كنزة',
      TypeBuy: 'WePay',
      Date: '14/1/2001',
      img: '../../defaultProduct.jfif',
      sizes: ['XL', 'L', 'M', 'S'],
      colors: ['#50d71e', '#000000', '#50d71e', '#000000'],
      fullName: 'غيث فيصل عثمان',
      email: 'ghaethoo2001.go@gmail.com',
      number: '+963937082264',
      city: 'حمص',
      Address: ' شارع الحضارة',
    },
    {
      typeOfCustumer: 'علي الديوب',
      TypeOfProduct: 'كنزة',
      TypeBuy: 'WePay',
      Date: '14/1/2001',
      img: '../../defaultProduct.jfif',
      sizes: ['XL', 'L', 'M', 'S'],
      colors: ['#50d71e', '#000000', '#50d71e', '#000000'],
      fullName: 'غيث فيصل عثمان',
      email: 'ghaethoo2001.go@gmail.com',
      number: '+963937082264',
      city: 'حمص',
      Address: ' شارع الحضارة',
    },
    {
      typeOfCustumer: 'ماريلا رحال',
      TypeOfProduct: 'كنزة',
      TypeBuy: 'WePay',
      Date: '14/1/2001',
      img: '../../defaultProduct.jfif',
      sizes: ['XL', 'L', 'M', 'S'],
      colors: ['#50d71e', '#000000', '#50d71e', '#000000'],
      fullName: 'غيث فيصل عثمان',
      email: 'ghaethoo2001.go@gmail.com',
      number: '+963937082264',
      city: 'حمص',
      Address: ' شارع الحضارة',
    },
    {
      typeOfCustumer: 'حسن المحمود',
      TypeOfProduct: 'كنزة',
      TypeBuy: 'WePay',
      Date: '14/1/2001',
      img: '../../defaultProduct.jfif',
      sizes: ['XL', 'L', 'M', 'S'],
      colors: ['#50d71e', '#000000', '#50d71e', '#000000'],
      fullName: 'غيث فيصل عثمان',
      email: 'ghaethoo2001.go@gmail.com',
      number: '+963937082264',
      city: 'حمص',
      Address: ' شارع الحضارة',
    },
    {
      typeOfCustumer: 'أحمد أحمد',
      TypeOfProduct: 'كنزة',
      TypeBuy: 'WePay',
      Date: '14/1/2001',
      img: '../../defaultProduct.jfif',
      sizes: ['XL', 'L', 'M', 'S'],
      colors: ['#50d71e', '#000000', '#50d71e', '#000000'],
      fullName: 'غيث فيصل عثمان',
      email: 'ghaethoo2001.go@gmail.com',
      number: '+963937082264',
      city: 'حمص',
      Address: ' شارع الحضارة',
    },
    {
      typeOfCustumer: 'علاء أحمد',
      TypeOfProduct: 'كنزة',
      TypeBuy: 'WePay',
      Date: '14/1/2001',
      img: '../../defaultProduct.jfif',
      sizes: ['XL', 'L', 'M', 'S'],
      colors: ['#50d71e', '#000000', '#50d71e', '#000000'],
      fullName: 'غيث فيصل عثمان',
      email: 'ghaethoo2001.go@gmail.com',
      number: '+963937082264',
      city: 'حمص',
      Address: ' شارع الحضارة',
    },
    {
      typeOfCustumer: 'ماريلا رحال',
      TypeOfProduct: 'كنزة',
      TypeBuy: 'WePay',
      Date: '14/1/2001',
      img: '../../defaultProduct.jfif',
      sizes: ['XL', 'L', 'M', 'S'],
      colors: ['#50d71e', '#000000', '#50d71e', '#000000'],
      fullName: 'غيث فيصل عثمان',
      email: 'ghaethoo2001.go@gmail.com',
      number: '+963937082264',
      city: 'حمص',
      Address: ' شارع الحضارة',
    },
    {
      typeOfCustumer: 'غيث عثمان',
      TypeOfProduct: 'كنزة',
      TypeBuy: 'WePay',
      Date: '14/1/2001',
      img: '../../defaultProduct.jfif',
      sizes: ['XL', 'L', 'M', 'S'],
      colors: ['#50d71e', '#000000', '#50d71e', '#000000'],
      fullName: 'غيث فيصل عثمان',
      email: 'ghaethoo2001.go@gmail.com',
      number: '+963937082264',
      city: 'حمص',
      Address: ' شارع الحضارة',
    },
    {
      typeOfCustumer: 'رونيا عودة',
      TypeOfProduct: 'كنزة',
      TypeBuy: 'WePay',
      Date: '14/1/2001',
      img: '../../defaultProduct.jfif',
      sizes: ['XL', 'L', 'M', 'S'],
      colors: ['#50d71e', '#000000', '#50d71e', '#000000'],
      fullName: 'غيث فيصل عثمان',
      email: 'ghaethoo2001.go@gmail.com',
      number: '+963937082264',
      city: 'حمص',
      Address: ' شارع الحضارة',
    },
    {
      typeOfCustumer: 'علي الديوب',
      TypeOfProduct: 'كنزة',
      TypeBuy: 'WePay',
      Date: '14/1/2001',
      img: '../../defaultProduct.jfif',
      sizes: ['XL', 'L', 'M', 'S'],
      colors: ['#50d71e', '#000000', '#50d71e', '#000000'],
      fullName: 'غيث فيصل عثمان',
      email: 'ghaethoo2001.go@gmail.com',
      number: '+963937082264',
      city: 'حمص',
      Address: ' شارع الحضارة',
    },
    {
      typeOfCustumer: 'ماريلا رحال',
      TypeOfProduct: 'كنزة',
      TypeBuy: 'WePay',
      Date: '14/1/2001',
      img: '../../defaultProduct.jfif',
      sizes: ['XL', 'L', 'M', 'S'],
      colors: ['#50d71e', '#000000', '#50d71e', '#000000'],
      fullName: 'غيث فيصل عثمان',
      email: 'ghaethoo2001.go@gmail.com',
      number: '+963937082264',
      city: 'حمص',
      Address: ' شارع الحضارة',
    },
    {
      typeOfCustumer: 'غيث عثمان',
      TypeOfProduct: 'كنزة',
      TypeBuy: 'WePay',
      Date: '14/1/2001',
      img: '../../defaultProduct.jfif',
      sizes: ['XL', 'L', 'M', 'S'],
      colors: ['#50d71e', '#000000', '#50d71e', '#000000'],
      fullName: 'غيث فيصل عثمان',
      email: 'ghaethoo2001.go@gmail.com',
      number: '+963937082264',
      city: 'حمص',
      Address: ' شارع الحضارة',
    },
    {
      typeOfCustumer: 'رونيا عودة',
      TypeOfProduct: 'كنزة',
      TypeBuy: 'WePay',
      Date: '14/1/2001',
      img: '../../defaultProduct.jfif',
      sizes: ['XL', 'L', 'M', 'S'],
      colors: ['#50d71e', '#000000', '#50d71e', '#000000'],
      fullName: 'غيث فيصل عثمان',
      email: 'ghaethoo2001.go@gmail.com',
      number: '+963937082264',
      city: 'حمص',
      Address: ' شارع الحضارة',
    },
    {
      typeOfCustumer: 'علي الديوب',
      TypeOfProduct: 'كنزة',
      TypeBuy: 'WePay',
      Date: '14/1/2001',
      img: '../../defaultProduct.jfif',
      sizes: ['XL', 'L', 'M', 'S'],
      colors: ['#50d71e', '#000000', '#50d71e', '#000000'],
      fullName: 'غيث فيصل عثمان',
      email: 'ghaethoo2001.go@gmail.com',
      number: '+963937082264',
      city: 'حمص',
      Address: ' شارع الحضارة',
    },
    {
      typeOfCustumer: 'ماريلا رحال',
      TypeOfProduct: 'كنزة',
      TypeBuy: 'WePay',
      Date: '14/1/2001',
      img: '../../defaultProduct.jfif',
      sizes: ['XL', 'L', 'M', 'S'],
      colors: ['#50d71e', '#000000', '#50d71e', '#000000'],
      fullName: 'غيث فيصل عثمان',
      email: 'ghaethoo2001.go@gmail.com',
      number: '+963937082264',
      city: 'حمص',
      Address: ' شارع الحضارة',
    },
    {
      typeOfCustumer: 'غيث عثمان',
      TypeOfProduct: 'كنزة',
      TypeBuy: 'WePay',
      Date: '14/1/2001',
      img: '../../defaultProduct.jfif',
      sizes: ['XL', 'L', 'M', 'S'],
      colors: ['#50d71e', '#000000', '#50d71e', '#000000'],
      fullName: 'غيث فيصل عثمان',
      email: 'ghaethoo2001.go@gmail.com',
      number: '+963937082264',
      city: 'حمص',
      Address: ' شارع الحضارة',
    },
    {
      typeOfCustumer: 'رونيا عودة',
      TypeOfProduct: 'كنزة',
      TypeBuy: 'WePay',
      Date: '14/1/2001',
      img: '../../defaultProduct.jfif',
      sizes: ['XL', 'L', 'M', 'S'],
      colors: ['#50d71e', '#000000', '#50d71e', '#000000'],
      fullName: 'غيث فيصل عثمان',
      email: 'ghaethoo2001.go@gmail.com',
      number: '+963937082264',
      city: 'حمص',
      Address: ' شارع الحضارة',
    },
    {
      typeOfCustumer: 'علي الديوب',
      TypeOfProduct: 'كنزة',
      TypeBuy: 'WePay',
      Date: '14/1/2001',
      img: '../../defaultProduct.jfif',
      sizes: ['XL', 'L', 'M', 'S'],
      colors: ['#50d71e', '#000000', '#50d71e', '#000000'],
      fullName: 'غيث فيصل عثمان',
      email: 'ghaethoo2001.go@gmail.com',
      number: '+963937082264',
      city: 'حمص',
      Address: ' شارع الحضارة',
    },
    {
      typeOfCustumer: 'ماريلا رحال',
      TypeOfProduct: 'كنزة',
      TypeBuy: 'WePay',
      Date: '14/1/2001',
      img: '../../defaultProduct.jfif',
      sizes: ['XL', 'L', 'M', 'S'],
      colors: ['#50d71e', '#000000', '#50d71e', '#000000'],
      fullName: 'غيث فيصل عثمان',
      email: 'ghaethoo2001.go@gmail.com',
      number: '+963937082264',
      city: 'حمص',
      Address: ' شارع الحضارة',
    },
    {
      typeOfCustumer: 'ماريلا رحال',
      TypeOfProduct: 'كنزة',
      TypeBuy: 'WePay',
      Date: '14/1/2001',
      img: '../../defaultProduct.jfif',
      sizes: ['XL', 'L', 'M', 'S'],
      colors: ['#50d71e', '#000000', '#50d71e', '#000000'],
      fullName: 'غيث فيصل عثمان',
      email: 'ghaethoo2001.go@gmail.com',
      number: '+963937082264',
      city: 'حمص',
      Address: ' شارع الحضارة',
    },
    {
      typeOfCustumer: 'غيث عثمان',
      TypeOfProduct: 'كنزة',
      TypeBuy: 'WePay',
      Date: '14/1/2001',
      img: '../../defaultProduct.jfif',
      sizes: ['XL', 'L', 'M', 'S'],
      colors: ['#50d71e', '#000000', '#50d71e', '#000000'],
      fullName: 'غيث فيصل عثمان',
      email: 'ghaethoo2001.go@gmail.com',
      number: '+963937082264',
      city: 'حمص',
      Address: ' شارع الحضارة',
    },
    {
      typeOfCustumer: 'رونيا عودة',
      TypeOfProduct: 'كنزة',
      TypeBuy: 'WePay',
      Date: '14/1/2001',
      img: '../../defaultProduct.jfif',
      sizes: ['XL', 'L', 'M', 'S'],
      colors: ['#50d71e', '#000000', '#50d71e', '#000000'],
      fullName: 'غيث فيصل عثمان',
      email: 'ghaethoo2001.go@gmail.com',
      number: '+963937082264',
      city: 'حمص',
      Address: ' شارع الحضارة',
    },
    {
      typeOfCustumer: 'علي الديوب',
      TypeOfProduct: 'كنزة',
      TypeBuy: 'WePay',
      Date: '14/1/2001',
      img: '../../defaultProduct.jfif',
      sizes: ['XL', 'L', 'M', 'S'],
      colors: ['#50d71e', '#000000', '#50d71e', '#000000'],
      fullName: 'غيث فيصل عثمان',
      email: 'ghaethoo2001.go@gmail.com',
      number: '+963937082264',
      city: 'حمص',
      Address: ' شارع الحضارة',
    },
    {
      typeOfCustumer: 'ماريلا رحال',
      TypeOfProduct: 'كنزة',
      TypeBuy: 'WePay',
      Date: '14/1/2001',
      img: '../../defaultProduct.jfif',
      sizes: ['XL', 'L', 'M', 'S'],
      colors: ['#50d71e', '#000000', '#50d71e', '#000000'],
      fullName: 'غيث فيصل عثمان',
      email: 'ghaethoo2001.go@gmail.com',
      number: '+963937082264',
      city: 'حمص',
      Address: ' شارع الحضارة',
    },
    {
      typeOfCustumer: 'حسن المحمود',
      TypeOfProduct: 'كنزة',
      TypeBuy: 'WePay',
      Date: '14/1/2001',
      img: '../../defaultProduct.jfif',
      sizes: ['XL', 'L', 'M', 'S'],
      colors: ['#50d71e', '#000000', '#50d71e', '#000000'],
      fullName: 'غيث فيصل عثمان',
      email: 'ghaethoo2001.go@gmail.com',
      number: '+963937082264',
      city: 'حمص',
      Address: ' شارع الحضارة',
    },
    {
      typeOfCustumer: 'أحمد أحمد',
      TypeOfProduct: 'كنزة',
      TypeBuy: 'WePay',
      Date: '14/1/2001',
      img: '../../defaultProduct.jfif',
      sizes: ['XL', 'L', 'M', 'S'],
      colors: ['#50d71e', '#000000', '#50d71e', '#000000'],
      fullName: 'غيث فيصل عثمان',
      email: 'ghaethoo2001.go@gmail.com',
      number: '+963937082264',
      city: 'حمص',
      Address: ' شارع الحضارة',
    },
    {
      typeOfCustumer: 'علاء أحمد',
      TypeOfProduct: 'كنزة',
      TypeBuy: 'WePay',
      Date: '14/1/2001',
      img: '../../defaultProduct.jfif',
      sizes: ['XL', 'L', 'M', 'S'],
      colors: ['#50d71e', '#000000', '#50d71e', '#000000'],
      fullName: 'غيث فيصل عثمان',
      email: 'ghaethoo2001.go@gmail.com',
      number: '+963937082264',
      city: 'حمص',
      Address: ' شارع الحضارة',
    },
    {
      typeOfCustumer: 'ماريلا رحال',
      TypeOfProduct: 'كنزة',
      TypeBuy: 'WePay',
      Date: '14/1/2001',
      img: '../../defaultProduct.jfif',
      sizes: ['XL', 'L', 'M', 'S'],
      colors: ['#50d71e', '#000000', '#50d71e', '#000000'],
      fullName: 'غيث فيصل عثمان',
      email: 'ghaethoo2001.go@gmail.com',
      number: '+963937082264',
      city: 'حمص',
      Address: ' شارع الحضارة',
    },
    {
      typeOfCustumer: 'غيث عثمان',
      TypeOfProduct: 'كنزة',
      TypeBuy: 'WePay',
      Date: '14/1/2001',
      img: '../../defaultProduct.jfif',
      sizes: ['XL', 'L', 'M', 'S'],
      colors: ['#50d71e', '#000000', '#50d71e', '#000000'],
      fullName: 'غيث فيصل عثمان',
      email: 'ghaethoo2001.go@gmail.com',
      number: '+963937082264',
      city: 'حمص',
      Address: ' شارع الحضارة',
    },
    {
      typeOfCustumer: 'رونيا عودة',
      TypeOfProduct: 'كنزة',
      TypeBuy: 'WePay',
      Date: '14/1/2001',
      img: '../../defaultProduct.jfif',
      sizes: ['XL', 'L', 'M', 'S'],
      colors: ['#50d71e', '#000000', '#50d71e', '#000000'],
      fullName: 'غيث فيصل عثمان',
      email: 'ghaethoo2001.go@gmail.com',
      number: '+963937082264',
      city: 'حمص',
      Address: ' شارع الحضارة',
    },
    {
      typeOfCustumer: 'علي الديوب',
      TypeOfProduct: 'كنزة',
      TypeBuy: 'WePay',
      Date: '14/1/2001',
      img: '../../defaultProduct.jfif',
      sizes: ['XL', 'L', 'M', 'S'],
      colors: ['#50d71e', '#000000', '#50d71e', '#000000'],
      fullName: 'غيث فيصل عثمان',
      email: 'ghaethoo2001.go@gmail.com',
      number: '+963937082264',
      city: 'حمص',
      Address: ' شارع الحضارة',
    },
    {
      typeOfCustumer: 'ماريلا رحال',
      TypeOfProduct: 'كنزة',
      TypeBuy: 'WePay',
      Date: '14/1/2001',
      img: '../../defaultProduct.jfif',
      sizes: ['XL', 'L', 'M', 'S'],
      colors: ['#50d71e', '#000000', '#50d71e', '#000000'],
      fullName: 'غيث فيصل عثمان',
      email: 'ghaethoo2001.go@gmail.com',
      number: '+963937082264',
      city: 'حمص',
      Address: ' شارع الحضارة',
    },
    {
      typeOfCustumer: 'غيث عثمان',
      TypeOfProduct: 'كنزة',
      TypeBuy: 'WePay',
      Date: '14/1/2001',
      img: '../../defaultProduct.jfif',
      sizes: ['XL', 'L', 'M', 'S'],
      colors: ['#50d71e', '#000000', '#50d71e', '#000000'],
      fullName: 'غيث فيصل عثمان',
      email: 'ghaethoo2001.go@gmail.com',
      number: '+963937082264',
      city: 'حمص',
      Address: ' شارع الحضارة',
    },
    {
      typeOfCustumer: 'رونيا عودة',
      TypeOfProduct: 'كنزة',
      TypeBuy: 'WePay',
      Date: '14/1/2001',
      img: '../../defaultProduct.jfif',
      sizes: ['XL', 'L', 'M', 'S'],
      colors: ['#50d71e', '#000000', '#50d71e', '#000000'],
      fullName: 'غيث فيصل عثمان',
      email: 'ghaethoo2001.go@gmail.com',
      number: '+963937082264',
      city: 'حمص',
      Address: ' شارع الحضارة',
    },
    {
      typeOfCustumer: 'علي الديوب',
      TypeOfProduct: 'كنزة',
      TypeBuy: 'WePay',
      Date: '14/1/2001',
      img: '../../defaultProduct.jfif',
      sizes: ['XL', 'L', 'M', 'S'],
      colors: ['#50d71e', '#000000', '#50d71e', '#000000'],
      fullName: 'غيث فيصل عثمان',
      email: 'ghaethoo2001.go@gmail.com',
      number: '+963937082264',
      city: 'حمص',
      Address: ' شارع الحضارة',
    },
    {
      typeOfCustumer: 'ماريلا رحال',
      TypeOfProduct: 'كنزة',
      TypeBuy: 'WePay',
      Date: '14/1/2001',
      img: '../../defaultProduct.jfif',
      sizes: ['XL', 'L', 'M', 'S'],
      colors: ['#50d71e', '#000000', '#50d71e', '#000000'],
      fullName: 'غيث فيصل عثمان',
      email: 'ghaethoo2001.go@gmail.com',
      number: '+963937082264',
      city: 'حمص',
      Address: ' شارع الحضارة',
    },
    {
      typeOfCustumer: 'غيث عثمان',
      TypeOfProduct: 'كنزة',
      TypeBuy: 'WePay',
      Date: '14/1/2001',
      img: '../../defaultProduct.jfif',
      sizes: ['XL', 'L', 'M', 'S'],
      colors: ['#50d71e', '#000000', '#50d71e', '#000000'],
      fullName: 'غيث فيصل عثمان',
      email: 'ghaethoo2001.go@gmail.com',
      number: '+963937082264',
      city: 'حمص',
      Address: ' شارع الحضارة',
    },
    {
      typeOfCustumer: 'رونيا عودة',
      TypeOfProduct: 'كنزة',
      TypeBuy: 'WePay',
      Date: '14/1/2001',
      img: '../../defaultProduct.jfif',
      sizes: ['XL', 'L', 'M', 'S'],
      colors: ['#50d71e', '#000000', '#50d71e', '#000000'],
      fullName: 'غيث فيصل عثمان',
      email: 'ghaethoo2001.go@gmail.com',
      number: '+963937082264',
      city: 'حمص',
      Address: ' شارع الحضارة',
    },
    {
      typeOfCustumer: 'علي الديوب',
      TypeOfProduct: 'كنزة',
      TypeBuy: 'WePay',
      Date: '14/1/2001',
      img: '../../defaultProduct.jfif',
      sizes: ['XL', 'L', 'M', 'S'],
      colors: ['#50d71e', '#000000', '#50d71e', '#000000'],
      fullName: 'غيث فيصل عثمان',
      email: 'ghaethoo2001.go@gmail.com',
      number: '+963937082264',
      city: 'حمص',
      Address: ' شارع الحضارة',
    },
    {
      typeOfCustumer: 'ماريلا رحال',
      TypeOfProduct: 'كنزة',
      TypeBuy: 'WePay',
      Date: '14/1/2001',
      img: '../../defaultProduct.jfif',
      sizes: ['XL', 'L', 'M', 'S'],
      colors: ['#50d71e', '#000000', '#50d71e', '#000000'],
      fullName: 'غيث فيصل عثمان',
      email: 'ghaethoo2001.go@gmail.com',
      number: '+963937082264',
      city: 'حمص',
      Address: ' شارع الحضارة',
    },
    {
      typeOfCustumer: 'ماريلا رحال',
      TypeOfProduct: 'كنزة',
      TypeBuy: 'WePay',
      Date: '14/1/2001',
      img: '../../defaultProduct.jfif',
      sizes: ['XL', 'L', 'M', 'S'],
      colors: ['#50d71e', '#000000', '#50d71e', '#000000'],
      fullName: 'غيث فيصل عثمان',
      email: 'ghaethoo2001.go@gmail.com',
      number: '+963937082264',
      city: 'حمص',
      Address: ' شارع الحضارة',
    },
  ]);
  const [ItemsDisplayed, setItemsDisplayed] = useState(items.slice(0, 10));
  const [FirstArrow, setFirstArrow] = useState(false);
  const [LastArrow, setLastArrow] = useState(true);
  // const [popUpIsOpen,setPopUpIsOpen]=useState(false);
  // functions
  const handleChange = (data) => {
    // for left arrow
    if (data.selected == 0) setFirstArrow(false);
    else setFirstArrow(true);
    // for right arrow
    if (data.selected == Math.ceil(items.length / 10) - 1) setLastArrow(false);
    else setLastArrow(true);

    setItemsDisplayed(items.slice(data.selected * 10, data.selected * 10 + 10));
  };
  return (
    <>
      <Navbar />
      <div className="pt-28 pb-10 flex flex-col w-full  ">
        <div className=" py-5 mb-3 w-full font-bold flex justify-center bg-gradient-to-l from-gradientFrom to-gradientTo dark:bg-gradient-to-tr dark:from-darkBgColor dark:to-darkTextColor2 text-white text-xl">
          مشترياتي
        </div>
        <div className="flex w-full flex-col md:flex-row justify-between px-10">
          <select className="mb-2 text-end md:mb-0 rounded shadow-sm hover:bg-slate-100  dark:hover:bg-darkTextColor2 dark:shadow-white">
            <option selected hidden>
              تصنيف حسب المعالجة
            </option>
            <option value="Done">تمت المعالجة</option>
            <option value="Processing">قيد المعالجة</option>
            <option value="NotYet">لم تتم المعالجة بعد</option>
          </select>
          <select className="rounded text-end shadow-sm hover:bg-slate-100  dark:hover:bg-darkTextColor2 dark:shadow-white">
            <option selected hidden>
              تصنيف حسب التاريخ
            </option>

            <option value="NTO">من الأحدث للأقدم</option>
            <option value="OTN">من الأقدم للأحدث</option>
          </select>
        </div>

        {ItemsDisplayed.map((item, index) => {
          return (
            <OneOrder value={item} key={index} page2={true} page1={false} />
          );
        })}
        <ReactPaginate
          breakLabel={<span className="md:mr-4 mr-1 text-white">...</span>}
          nextLabel={
            LastArrow ? (
              <span className="w-4 h-4 md:w-10 md:h-10 flex items-center hover:bg-textColor dark:hover:bg-gray-500 justify-center text-white rounded-md">
                <BsChevronRight />
              </span>
            ) : null
          }
          onPageChange={handleChange}
          pageRangeDisplayed={1}
          pageCount={items.length / 10}
          previousLabel={
            FirstArrow ? (
              <span className="text-white hover:bg-textColor dark:hover:bg-gray-500 w-4 h-4 md:w-10 md:h-10 flex items-center justify-center rounded-md mr-4">
                <BsChevronLeft />
              </span>
            ) : null
          }
          containerClassName="flex items-center justify-center mt-8 mb-4 bg-gradient-to-l from-gradientFrom to-gradientTo dark:bg-gradient-to-tr dark:from-darkBgColor dark:to-darkTextColor2 "
          pageClassName="block border- border-solid text-white border-lightGray hover:bg-textColor dark:hover:bg-gray-500 text-sm md:text-lg w-2  md:w-10 h-10 flex items-center justify-center rounded-md mr-4"
          activeClassName=" text-lg font-bold"
        />
      </div>
    </>
  );
}

export default MyPurchases;
